/* Curated German starter deck and original graded stories. */
window.GERMAN_WORDS = [
  {w:"ich",d:"I; me",l:"A1",t:"pronoun",f:["mich","mir"],n:"Always written lowercase unless it begins a sentence."},
  {w:"du",d:"you (informal singular)",l:"A1",t:"pronoun",f:["dich","dir"],n:"Use du with friends, family, and children."},
  {w:"er",d:"he; him",l:"A1",t:"pronoun",f:["ihm","ihn"]},{w:"sie",d:"she; they; you (formal)",l:"A1",t:"pronoun",n:"Capitalized Sie is the formal ‘you’."},{w:"es",d:"it",l:"A1",t:"pronoun"},{w:"wir",d:"we; us",l:"A1",t:"pronoun",f:["uns"]},{w:"ihr",d:"you (informal plural)",l:"A1",t:"pronoun"},
  {w:"der",d:"the (masculine)",l:"A1",t:"article",f:["den","dem","des"]},{w:"die",d:"the (feminine or plural)",l:"A1",t:"article"},{w:"das",d:"the (neuter)",l:"A1",t:"article"},{w:"ein",d:"a; an (masculine or neuter)",l:"A1",t:"article",f:["einen","einem","eines"]},{w:"eine",d:"a; an (feminine)",l:"A1",t:"article",f:["einer"]},
  {w:"mein",d:"my",l:"A1",t:"determiner",f:["meine","meinen","meinem","meiner"]},{w:"dein",d:"your",l:"A1",t:"determiner",f:["deine","deinen","deinem","deiner"]},
  {w:"sein",d:"to be",l:"A1",t:"verb",f:["bin","bist","ist","sind","seid","war","waren"],n:"ich bin · du bist · er/sie/es ist"},
  {w:"haben",d:"to have",l:"A1",t:"verb",f:["habe","hast","hat","habt","hatte","hatten"]},
  {w:"heißen",d:"to be called",l:"A1",t:"verb",f:["heiße","heißt"]},{w:"wohnen",d:"to live; reside",l:"A1",t:"verb",f:["wohne","wohnst","wohnt"]},{w:"kommen",d:"to come; come from",l:"A1",t:"verb",f:["komme","kommst","kommt","kam","komm"]},{w:"gehen",d:"to go; walk",l:"A1",t:"verb",f:["gehe","gehst","geht","ging"]},
  {w:"machen",d:"to do; make",l:"A1",t:"verb",f:["mache","machst","macht","machte"]},{w:"lernen",d:"to learn; study",l:"A1",t:"verb",f:["lerne","lernst","lernt"]},{w:"lesen",d:"to read",l:"A1",t:"verb",f:["lese","liest","las"]},{w:"sprechen",d:"to speak",l:"A1",t:"verb",f:["spreche","sprich","sprichst","spricht","sprach"]},{w:"verstehen",d:"to understand",l:"A1",t:"verb",f:["verstehe","verstehst","versteht","verstand"]},
  {w:"sehen",d:"to see",l:"A1",t:"verb",f:["sehe","siehst","sieht","sah"]},{w:"hören",d:"to hear; listen",l:"A1",t:"verb",f:["höre","hörst","hört"]},{w:"wissen",d:"to know (a fact)",l:"A2",t:"verb",f:["weiß","weißt","wissen","wusste"]},{w:"wollen",d:"to want",l:"A1",t:"modal verb",f:["will","willst","wollt","wollte"]},{w:"können",d:"can; to be able to",l:"A1",t:"modal verb",f:["kann","kannst","könnt","konnte"]},
  {w:"müssen",d:"must; to have to",l:"A1",t:"modal verb",f:["muss","musst","müsst","musste"]},{w:"mögen",d:"to like",l:"A1",t:"verb",f:["mag","magst","mögt","mochte"]},{w:"lieben",d:"to love",l:"A1",t:"verb",f:["liebe","liebst","liebt"]},{w:"geben",d:"to give; there is/are",l:"A1",t:"verb",f:["gebe","gibst","gibt","gab"]},{w:"nehmen",d:"to take",l:"A1",t:"verb",f:["nehme","nimmst","nimmt","nahm"]},
  {w:"finden",d:"to find; think (an opinion)",l:"A1",t:"verb",f:["finde","findest","findet","fand"]},{w:"arbeiten",d:"to work",l:"A1",t:"verb",f:["arbeite","arbeitest","arbeitet"]},{w:"kaufen",d:"to buy",l:"A1",t:"verb",f:["kaufe","kaufst","kauft"]},{w:"essen",d:"to eat",l:"A1",t:"verb",f:["esse","isst","esst","aß"]},{w:"trinken",d:"to drink",l:"A1",t:"verb",f:["trinke","trinkst","trinkt","trank"]},
  {w:"schlafen",d:"to sleep",l:"A1",t:"verb",f:["schlafe","schläfst","schläft","schlief"]},{w:"bleiben",d:"to stay; remain",l:"A2",t:"verb",f:["bleibe","bleibst","bleibt","blieb"]},{w:"treffen",d:"to meet",l:"A2",t:"verb",f:["treffe","triffst","trifft","traf"]},{w:"warten",d:"to wait",l:"A1",t:"verb",f:["warte","wartest","wartet"]},{w:"fahren",d:"to travel; drive; ride",l:"A1",t:"verb",f:["fahre","fährst","fährt","fuhr"]},
  {w:"regnen",d:"to rain",l:"A1",t:"verb",f:["regnet","regnete"]},{w:"lachen",d:"to laugh",l:"A1",t:"verb",f:["lache","lachst","lacht"]},{w:"sagen",d:"to say",l:"A1",t:"verb",f:["sage","sagst","sagt","sagte"]},{w:"fragen",d:"to ask",l:"A1",t:"verb",f:["frage","fragst","fragt","fragte"]},{w:"antworten",d:"to answer",l:"A1",t:"verb",f:["antworte","antwortet","antwortete"]},
  {w:"ankommen",d:"to arrive",l:"A2",t:"separable verb",f:["angekommen"]},{w:"einsteigen",d:"to get in; board",l:"A2",t:"separable verb",f:["eingestiegen"]},{w:"aussteigen",d:"to get out; alight",l:"A2",t:"separable verb",f:["ausgestiegen"]},{w:"anrufen",d:"to call by phone",l:"A2",t:"separable verb",f:["ruft","angerufen"]},
  {w:"Mann",a:"der",p:"Männer",d:"man",l:"A1",t:"noun",f:["mann","männer"]},{w:"Frau",a:"die",p:"Frauen",d:"woman; Mrs",l:"A1",t:"noun",f:["frau","frauen"]},{w:"Kind",a:"das",p:"Kinder",d:"child",l:"A1",t:"noun",f:["kind","kinder"]},{w:"Freund",a:"der",p:"Freunde",d:"friend; boyfriend",l:"A1",t:"noun",f:["freund","freunde","freundin","freundinnen"]},{w:"Familie",a:"die",p:"Familien",d:"family",l:"A1",t:"noun",f:["familie","familien"]},
  {w:"Name",a:"der",p:"Namen",d:"name",l:"A1",t:"noun",f:["name","namen"]},{w:"Stadt",a:"die",p:"Städte",d:"city; town",l:"A1",t:"noun",f:["stadt","städte"]},{w:"Haus",a:"das",p:"Häuser",d:"house; building",l:"A1",t:"noun",f:["haus","häuser","hause"]},{w:"Wohnung",a:"die",p:"Wohnungen",d:"apartment; flat",l:"A1",t:"noun",f:["wohnung","wohnungen"]},{w:"Zimmer",a:"das",p:"Zimmer",d:"room",l:"A1",t:"noun",f:["zimmer"]},
  {w:"Tag",a:"der",p:"Tage",d:"day",l:"A1",t:"noun",f:["tag","tage"]},{w:"Morgen",a:"der",p:"Morgen",d:"morning",l:"A1",t:"noun",f:["morgen"]},{w:"Abend",a:"der",p:"Abende",d:"evening",l:"A1",t:"noun",f:["abend","abends"]},{w:"Zeit",a:"die",p:"Zeiten",d:"time",l:"A1",t:"noun",f:["zeit","zeiten"]},{w:"Arbeit",a:"die",p:"—",d:"work; job",l:"A1",t:"noun",f:["arbeit"]},
  {w:"Schule",a:"die",p:"Schulen",d:"school",l:"A1",t:"noun",f:["schule","schulen"]},{w:"Buch",a:"das",p:"Bücher",d:"book",l:"A1",t:"noun",f:["buch","bücher"]},{w:"Wort",a:"das",p:"Wörter",d:"word",l:"A1",t:"noun",f:["wort","wörter","worten"]},{w:"Sprache",a:"die",p:"Sprachen",d:"language",l:"A1",t:"noun",f:["sprache","sprachen"]},{w:"Deutsch",d:"German (language)",l:"A1",t:"language",f:["deutsch","deutsche","deutschen","deutscher","deutsches"]},
  {w:"Kaffee",a:"der",p:"—",d:"coffee",l:"A1",t:"noun",f:["kaffee"]},{w:"Tee",a:"der",p:"Tees",d:"tea",l:"A1",t:"noun",f:["tee","tees"]},{w:"Wasser",a:"das",p:"—",d:"water",l:"A1",t:"noun",f:["wasser"]},{w:"Brot",a:"das",p:"Brote",d:"bread",l:"A1",t:"noun",f:["brot","brote"]},{w:"Käse",a:"der",p:"—",d:"cheese",l:"A1",t:"noun",f:["käse"]},{w:"Apfel",a:"der",p:"Äpfel",d:"apple",l:"A1",t:"noun",f:["apfel","äpfel"]},
  {w:"Bahnhof",a:"der",p:"Bahnhöfe",d:"train station",l:"A1",t:"noun",f:["bahnhof","bahnhöfe"]},{w:"Zug",a:"der",p:"Züge",d:"train",l:"A1",t:"noun",f:["zug","züge"]},{w:"Fahrrad",a:"das",p:"Fahrräder",d:"bicycle",l:"A1",t:"noun",f:["fahrrad","fahrräder"]},{w:"Straße",a:"die",p:"Straßen",d:"street; road",l:"A1",t:"noun",f:["straße","straßen"]},{w:"Regen",a:"der",p:"—",d:"rain",l:"A1",t:"noun",f:["regen"]},{w:"Sonne",a:"die",p:"Sonnen",d:"sun",l:"A1",t:"noun",f:["sonne","sonnen"]},
  {w:"Café",a:"das",p:"Cafés",d:"café",l:"A1",t:"noun",f:["café","cafés"]},{w:"Spaß",a:"der",p:"—",d:"fun",l:"A1",t:"noun",f:["spaß"]},{w:"Bahnhofshalle",a:"die",p:"Bahnhofshallen",d:"station hall",l:"B1",t:"noun",f:["bahnhofshalle","bahnhofshallen"]},{w:"Bahnsteig",a:"der",p:"Bahnsteige",d:"platform",l:"A2",t:"noun",f:["bahnsteig","bahnsteige"]},{w:"Verspätung",a:"die",p:"Verspätungen",d:"delay",l:"A2",t:"noun",f:["verspätung","verspätungen"]},{w:"Durchsage",a:"die",p:"Durchsagen",d:"announcement",l:"B1",t:"noun",f:["durchsage","durchsagen"]},{w:"Fahrkarte",a:"die",p:"Fahrkarten",d:"ticket",l:"A2",t:"noun",f:["fahrkarte","fahrkarten"]},
  {w:"Freitagabend",a:"der",p:"Freitagabende",d:"Friday evening",l:"A2",t:"noun",f:["freitagabend","freitagabende"]},{w:"Mensch",a:"der",p:"Menschen",d:"person; human being",l:"A1",t:"noun",f:["mensch","menschen"]},{w:"Mutter",a:"die",p:"Mütter",d:"mother",l:"A1",t:"noun",f:["mutter","mütter"]},{w:"Geburtstag",a:"der",p:"Geburtstage",d:"birthday",l:"A1",t:"noun",f:["geburtstag","geburtstage"]},{w:"Auto",a:"das",p:"Autos",d:"car",l:"A1",t:"noun",f:["auto","autos"]},
  {w:"Platz",a:"der",p:"Plätze",d:"place; seat; square",l:"A1",t:"noun",f:["platz","plätze"]},{w:"Stunde",a:"die",p:"Stunden",d:"hour",l:"A1",t:"noun",f:["stunde","stunden"]},{w:"Anfang",a:"der",p:"Anfänge",d:"beginning",l:"A2",t:"noun",f:["anfang","anfänge"]},{w:"Geschichte",a:"die",p:"Geschichten",d:"story; history",l:"A2",t:"noun",f:["geschichte","geschichten"]},{w:"Glück",a:"das",p:"—",d:"luck; happiness",l:"A2",t:"noun",f:["glück","glückstag"]},
  {w:"gut",d:"good; well",l:"A1",t:"adjective",f:["gute","guten","guter","gutes","besser","beste","besten"]},{w:"klein",d:"small",l:"A1",t:"adjective",f:["kleine","kleinen","kleiner","kleines"]},{w:"groß",d:"big; tall",l:"A1",t:"adjective",f:["große","großen","großer","großes"]},{w:"schön",d:"beautiful; nice",l:"A1",t:"adjective",f:["schöne","schönen","schöner","schönes"]},{w:"neu",d:"new",l:"A1",t:"adjective",f:["neue","neuen","neuer","neues"]},{w:"alt",d:"old",l:"A1",t:"adjective",f:["alte","alten","alter","älter"]},
  {w:"schnell",d:"fast; quickly",l:"A1",t:"adjective",f:["schnelle","schnellen"]},{w:"langsam",d:"slow; slowly",l:"A1",t:"adjective",f:["langsame","langsamen"]},{w:"spät",d:"late",l:"A1",t:"adjective",f:["späte","späten"]},{w:"müde",d:"tired",l:"A1",t:"adjective"},{w:"glücklich",d:"happy; fortunate",l:"A2",t:"adjective",f:["glückliche","glücklichen"]},{w:"frei",d:"free; available",l:"A1",t:"adjective",f:["freie","freien"]},{w:"kalt",d:"cold",l:"A1",t:"adjective",f:["kalte","kalten"]},{w:"warm",d:"warm",l:"A1",t:"adjective",f:["warme","warmen"]},{w:"wichtig",d:"important",l:"A2",t:"adjective",f:["wichtige","wichtigen"]},{w:"leicht",d:"easy; light",l:"A1",t:"adjective",f:["leichte","leichten"]},{w:"letzt",d:"last; final",l:"A2",t:"adjective",f:["letzte","letzten","letzter","letztes"]},{w:"kein",d:"no; not a; none",l:"A1",t:"determiner",f:["keine","keinen","keinem","keiner"]},
  {w:"heute",d:"today",l:"A1",t:"adverb"},{w:"gestern",d:"yesterday",l:"A1",t:"adverb"},{w:"jetzt",d:"now",l:"A1",t:"adverb"},{w:"hier",d:"here",l:"A1",t:"adverb"},{w:"dort",d:"there",l:"A1",t:"adverb"},{w:"gern",d:"gladly; like to",l:"A1",t:"adverb",f:["gerne"]},{w:"sehr",d:"very",l:"A1",t:"adverb"},{w:"auch",d:"also; too",l:"A1",t:"adverb"},{w:"nicht",d:"not",l:"A1",t:"adverb"},{w:"noch",d:"still; another",l:"A1",t:"adverb"},{w:"schon",d:"already",l:"A1",t:"adverb"},{w:"nur",d:"only",l:"A1",t:"adverb"},{w:"viel",d:"much; a lot",l:"A1",t:"quantifier",f:["viele","vielen"]},{w:"manchmal",d:"sometimes",l:"A1",t:"adverb"},{w:"später",d:"later",l:"A1",t:"adverb"},{w:"vorbei",d:"over; past",l:"A2",t:"adverb"},{w:"beide",d:"both",l:"A2",t:"quantifier"},
  {w:"in",d:"in; into",l:"A1",t:"preposition",f:["im","ins"]},{w:"aus",d:"out of; from",l:"A1",t:"preposition"},{w:"mit",d:"with; by",l:"A1",t:"preposition"},{w:"nach",d:"after; to",l:"A1",t:"preposition"},{w:"zu",d:"to; too",l:"A1",t:"preposition",f:["zur","zum"]},{w:"auf",d:"on; onto",l:"A1",t:"preposition"},{w:"für",d:"for",l:"A1",t:"preposition"},{w:"von",d:"from; of",l:"A1",t:"preposition"},{w:"bei",d:"at; with",l:"A1",t:"preposition"},{w:"ohne",d:"without",l:"A2",t:"preposition"},{w:"an",d:"at; on",l:"A1",t:"preposition",f:["am"]},{w:"neben",d:"next to; beside",l:"A1",t:"preposition"},{w:"vor",d:"in front of; before",l:"A1",t:"preposition"},{w:"bis",d:"until; as far as",l:"A1",t:"preposition"},{w:"durch",d:"through",l:"A1",t:"preposition"},{w:"um",d:"around; at (a time)",l:"A1",t:"preposition"},{w:"als",d:"as; than; when",l:"A2",t:"connector"},
  {w:"und",d:"and",l:"A1",t:"connector"},{w:"aber",d:"but",l:"A1",t:"connector"},{w:"oder",d:"or",l:"A1",t:"connector"},{w:"weil",d:"because",l:"A2",t:"connector",n:"The conjugated verb moves to the end of the clause."},{w:"wenn",d:"if; whenever; when",l:"A2",t:"connector"},{w:"dann",d:"then",l:"A1",t:"adverb"},{w:"dass",d:"that",l:"A2",t:"connector"},{w:"denn",d:"because; for",l:"A2",t:"connector"},
  {w:"wer",d:"who",l:"A1",t:"question word"},{w:"was",d:"what",l:"A1",t:"question word"},{w:"wo",d:"where",l:"A1",t:"question word"},{w:"wie",d:"how; what … like",l:"A1",t:"question word"},{w:"warum",d:"why",l:"A1",t:"question word"},{w:"wann",d:"when",l:"A1",t:"question word"},
  {w:"stehen",d:"to stand",l:"A1",t:"verb",f:["stehe","stehst","steht","stand"]},{w:"denken",d:"to think",l:"A2",t:"verb",f:["denke","denkst","denkt","dachte"]},{w:"steigen",d:"to climb; rise",l:"A2",t:"verb",f:["steige","steigst","steigt","stieg"]},{w:"werden",d:"to become; will",l:"A2",t:"verb",f:["werde","wirst","wird","werden","wurde"]},{w:"besuchen",d:"to visit",l:"A1",t:"verb",f:["besuche","besuchst","besucht"]},{w:"zeigen",d:"to show",l:"A1",t:"verb",f:["zeige","zeigst","zeigt"]},{w:"öffnen",d:"to open",l:"A1",t:"verb",f:["öffne","öffnest","öffnet"]},{w:"schreiben",d:"to write",l:"A1",t:"verb",f:["schreibe","schreibst","schreibt","schrieb"]},{w:"brauchen",d:"to need",l:"A1",t:"verb",f:["brauche","brauchst","braucht"]},{w:"bringen",d:"to bring",l:"A2",t:"verb",f:["bringe","bringst","bringt","brachte"]},{w:"scheinen",d:"to shine; seem",l:"A2",t:"verb",f:["scheine","scheint","schien"]},{w:"kennen",d:"to know; be familiar with",l:"A1",t:"verb",f:["kenne","kennst","kennt","kannte"]},
  {w:"Jahr",a:"das",p:"Jahre",d:"year",l:"A1",t:"noun",f:["jahr","jahre"]},{w:"Zuhause",a:"das",p:"—",d:"home",l:"A1",t:"noun",f:["zuhause"]},{w:"Uhr",a:"die",p:"Uhren",d:"clock; o’clock",l:"A1",t:"noun",f:["uhr","uhren"]},{w:"Sonntag",a:"der",p:"Sonntage",d:"Sunday",l:"A1",t:"noun",f:["sonntag","sonntage"]},{w:"Samstag",a:"der",p:"Samstage",d:"Saturday",l:"A1",t:"noun",f:["samstag","samstage"]},{w:"Mitte",a:"die",p:"—",d:"middle; center",l:"A2",t:"noun",f:["mitte"]},{w:"Weg",a:"der",p:"Wege",d:"way; path",l:"A1",t:"noun",f:["weg","wege"]},{w:"Mittag",a:"der",p:"Mittage",d:"midday; lunch",l:"A1",t:"noun",f:["mittag"]},{w:"Fenster",a:"das",p:"Fenster",d:"window",l:"A1",t:"noun",f:["fenster"]},{w:"Bild",a:"das",p:"Bilder",d:"picture; image",l:"A1",t:"noun",f:["bild","bilder"]},{w:"Nachricht",a:"die",p:"Nachrichten",d:"message; news",l:"A2",t:"noun",f:["nachricht","nachrichten"]},{w:"Stimme",a:"die",p:"Stimmen",d:"voice",l:"A2",t:"noun",f:["stimme","stimmen"]},{w:"Telefon",a:"das",p:"Telefone",d:"telephone",l:"A1",t:"noun",f:["telefon","telefone"]},{w:"Markt",a:"der",p:"Märkte",d:"market",l:"A1",t:"noun",f:["markt","märkte"]},{w:"Plan",a:"der",p:"Pläne",d:"plan",l:"A2",t:"noun",f:["plan","pläne"]},{w:"Leben",a:"das",p:"—",d:"life",l:"A2",t:"noun",f:["leben"]},{w:"Antwort",a:"die",p:"Antworten",d:"answer",l:"A1",t:"noun",f:["antwort"]},{w:"Minute",a:"die",p:"Minuten",d:"minute",l:"A1",t:"noun",f:["minute","minuten"]},
  {w:"ruhig",d:"quiet; calm",l:"A2",t:"adjective"},{w:"weit",d:"far; wide",l:"A1",t:"adjective"},{w:"weiter",d:"further; another",l:"A2",t:"adjective",f:["weitere","weiteren","weiterer","weiteres"]},{w:"nächst",d:"next; nearest",l:"A2",t:"adjective",f:["nächste","nächsten","nächster","nächstes"]},{w:"kurz",d:"short; briefly",l:"A1",t:"adjective",f:["kurze","kurzen","kurzer","kurzes"]},{w:"schwer",d:"difficult; heavy",l:"A1",t:"adjective"},{w:"ganz",d:"whole; quite",l:"A1",t:"adjective",f:["ganze","ganzen","ganzer","ganzes"]},{w:"erst",d:"first; only",l:"A1",t:"adjective",f:["erste","ersten","erster","erstes"]},{w:"zusammen",d:"together",l:"A1",t:"adverb"},{w:"wieder",d:"again",l:"A1",t:"adverb"},{w:"mehr",d:"more",l:"A1",t:"adverb"},{w:"fast",d:"almost",l:"A2",t:"adverb"},{w:"oft",d:"often",l:"A1",t:"adverb"},{w:"immer",d:"always",l:"A1",t:"adverb"},{w:"so",d:"so; like that",l:"A1",t:"adverb"},{w:"endlich",d:"finally",l:"A2",t:"adverb"},{w:"dazu",d:"with it; in addition",l:"A2",t:"adverb"},{w:"jeder",d:"each; every",l:"A2",t:"determiner",f:["jede","jeden","jedem","jeder","jedes"]},{w:"andere",d:"other",l:"A2",t:"determiner",f:["anderen","anderer","anderes"]},{w:"dieser",d:"this",l:"A1",t:"determiner",f:["diese","diesen","diesem","dieser","dieses"]},{w:"acht",d:"eight",l:"A1",t:"number"},{w:"zehn",d:"ten",l:"A1",t:"number"},{w:"zwanzig",d:"twenty",l:"A1",t:"number"},
  {w:"Erfahrung",a:"die",p:"Erfahrungen",d:"experience",l:"B1",t:"noun",f:["erfahrung","erfahrungen"]},{w:"Möglichkeit",a:"die",p:"Möglichkeiten",d:"possibility; option",l:"B1",t:"noun",f:["möglichkeit","möglichkeiten"]},{w:"Entscheidung",a:"die",p:"Entscheidungen",d:"decision",l:"B1",t:"noun",f:["entscheidung","entscheidungen"]},{w:"Verhalten",a:"das",p:"—",d:"behavior",l:"B1",t:"noun",f:["verhalten"]},{w:"Umgebung",a:"die",p:"Umgebungen",d:"surroundings; area",l:"B1",t:"noun",f:["umgebung","umgebungen"]},
  {w:"trotzdem",d:"nevertheless; even so",l:"B1",t:"connector"},{w:"obwohl",d:"although",l:"B1",t:"connector",n:"The conjugated verb moves to the end of the clause."},{w:"während",d:"while; during",l:"B1",t:"connector"},{w:"deshalb",d:"therefore; that is why",l:"B1",t:"connector"},{w:"wahrscheinlich",d:"probably",l:"B1",t:"adverb"},{w:"erzählen",d:"to tell; narrate",l:"B1",t:"verb",f:["erzähle","erzählst","erzählt","erzählte"]},{w:"entscheiden",d:"to decide",l:"B1",t:"verb",f:["entscheide","entscheidest","entscheidet","entschied"]},{w:"bemerken",d:"to notice",l:"B1",t:"verb",f:["bemerke","bemerkst","bemerkt"]},{w:"gehören",d:"to belong",l:"B1",t:"verb",f:["gehöre","gehörst","gehört"]},{w:"vorstellen",d:"to introduce; imagine",l:"B1",t:"separable verb",f:["vorgestellt"]},
  {w:"Hallo",d:"hello",l:"A1",t:"phrase",f:["hallo"]},{w:"Guten Morgen",d:"good morning",l:"A1",t:"phrase"},{w:"Danke",d:"thank you",l:"A1",t:"phrase",f:["danke"]},{w:"Bitte",d:"please; you’re welcome",l:"A1",t:"phrase",f:["bitte"]},{w:"Tschüss",d:"bye",l:"A1",t:"phrase",f:["tschüss"]},{w:"ja",d:"yes",l:"A1",t:"response"},{w:"nein",d:"no",l:"A1",t:"response"}
];

window.GERMAN_STORIES = {
  beginner: {
    title: "Ein Tag in Berlin",
    level: "A1 · Beginner",
    intro: "A short first story about Mia’s new life in Berlin. Tap any underlined word for meaning, grammar, and audio.",
    chapters: [
      {title:"Hallo, Berlin", paragraphs:[
        {de:"Hallo! Ich heiße Mia. Ich komme aus Dublin und lerne Deutsch. Jetzt wohne ich in Berlin.",en:"Hello! My name is Mia. I come from Dublin and I’m learning German. I now live in Berlin."},
        {de:"Die Stadt ist groß, aber meine Wohnung ist klein. Sie hat ein Zimmer. Ich finde sie sehr schön.",en:"The city is big, but my apartment is small. It has one room. I think it is very nice."}
      ]},
      {title:"Der Morgen", paragraphs:[
        {de:"Am Morgen trinke ich Kaffee und esse Brot mit Käse. Dann fahre ich mit dem Zug zur Arbeit.",en:"In the morning I drink coffee and eat bread with cheese. Then I take the train to work."},
        {de:"Der Zug ist schnell. Ich lese ein Buch und höre Deutsch. Ich verstehe schon viel.",en:"The train is fast. I read a book and listen to German. I already understand a lot."}
      ]},
      {title:"Ein neuer Freund", paragraphs:[
        {de:"Bei der Arbeit treffe ich Jonas. Er ist mein neuer Freund. Wir sprechen langsam Deutsch.",en:"At work I meet Jonas. He is my new friend. We speak German slowly."},
        {de:"Jonas fragt: Magst du Berlin? Ich antworte: Ja, sehr. Aber der Regen ist kalt.",en:"Jonas asks: Do you like Berlin? I answer: Yes, very much. But the rain is cold."}
      ]},
      {title:"Feierabend", paragraphs:[
        {de:"Am Abend gehen wir in ein kleines Café. Jonas nimmt Tee. Ich nehme Wasser und einen Apfel.",en:"In the evening we go to a small café. Jonas has tea. I have water and an apple."},
        {de:"Wir lachen und sagen: Deutsch ist nicht leicht, aber es macht Spaß. Tschüss, bis morgen!",en:"We laugh and say: German isn’t easy, but it is fun. Bye, see you tomorrow!"}
      ]}
    ]
  },
  intermediate: {
    title: "Der letzte Zug",
    level: "A2–B1 · Short story",
    intro: "A rainy station, a delayed train, and a small decision. Read naturally; use the translation only when you need it.",
    chapters: [
      {title:"Verspätung", paragraphs:[
        {de:"Freitagabend. Lena wartet am Bahnhof. Der letzte Zug nach Hamburg hat Verspätung. Auf dem Bahnsteig stehen nur drei Menschen.",en:"Friday evening. Lena is waiting at the station. The last train to Hamburg is delayed. Only three people are standing on the platform."},
        {de:"Es regnet, und Lena ist müde. Sie will nach Hause. Die Mutter von Lena hat morgen Geburtstag.",en:"It is raining, and Lena is tired. She wants to go home. Lena’s mother has her birthday tomorrow."}
      ]},
      {title:"Die Durchsage", paragraphs:[
        {de:"Dann kommt eine Durchsage: Der Zug fährt heute nicht. Bitte warten Sie in der Bahnhofshalle.",en:"Then an announcement comes: The train will not run today. Please wait in the station hall."},
        {de:"Ein alter Mann neben Lena lacht. Das ist mein Glückstag, sagt er. Ich habe auch keine Fahrkarte.",en:"An old man next to Lena laughs. This is my lucky day, he says. I don’t have a ticket either."}
      ]},
      {title:"Eine Idee", paragraphs:[
        {de:"Der Mann heißt Paul. Die Familie von Paul wohnt auch in Hamburg. Lena fragt: Haben Sie ein Auto? Paul antwortet: Nein, aber ich habe ein Fahrrad.",en:"The man’s name is Paul. Paul’s family also lives in Hamburg. Lena asks: Do you have a car? Paul answers: No, but I have a bicycle."},
        {de:"Beide lachen. Dann findet Lena eine Frau mit einem kleinen Auto. Sie fährt nach Hamburg und hat noch zwei Plätze frei.",en:"They both laugh. Then Lena finds a woman with a small car. She is driving to Hamburg and still has two seats free."}
      ]},
      {title:"Ankunft", paragraphs:[
        {de:"Drei Stunden später kommen sie in Hamburg an. Der Regen ist vorbei. Die Mutter von Lena wartet vor dem Haus.",en:"Three hours later they arrive in Hamburg. The rain is over. Lena’s mother is waiting in front of the house."},
        {de:"Manchmal, denkt Lena, ist eine Verspätung nur der Anfang von einer guten Geschichte.",en:"Sometimes, Lena thinks, a delay is only the beginning of a good story."}
      ]}
    ]
  }
};
